name: Build & Release
on: [push]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - run: yarn install
      - run: yarn zuplo build
        env:
          GIT_SHA: ${{ github.sha }}
          API_VERSION: ${{ github.run_id }}
      - run: yarn lint

      - uses: zuplo/deploy-zup-action@main
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          project: zuplo-ecommerce-api
          account_id: 4f59a390b9f139a4a82b757edd3c71dd
          api_token: ${{ secrets.ZUPLO_CF_API_TOKEN }}
